File = "/configs/export/config.toml"

[exp]
  cache_db = "0"
  cache_pass = ""
  cache_url = "localhost:6379"
  log_level = "debug"
  nats = "nats://broker:4222"
  port = "8170"

[mqtt]
  ca_path = ""
  client_cert = ""
  client_cert_key = ""
  client_cert_path = ""
  client_priv_key_path = ""
  host = "tcp://mqtt-adapter:1883"
  mtls = false
  password = "7c655598-38bf-46de-abba-f1b377461a44"
  qos = 0
  retain = false
  skip_tls_ver = true
  username = "bff01a80-a16d-4828-abe2-30e8f3f27b83"

[[routes]]
  mqtt_topic = "channels/05ff7d0b-62be-433a-9eff-cd963b4c6b5d/messages"
  nats_topic = "export"
  subtopic = ""
## default means that payload sent on NATS will be just forwarded to MQTT
  type = "default"
## Number of the workers depends on the connection capacity
## as well as on payload size that needs to be sent.
## Number of workers also determines the size of the buffer
## that recieves messages from NATS.
## For regular telemetry SenML messages 10 workers is enough.
  workers = 10

[[routes]]
  mqtt_topic = "channels/05ff7d0b-62be-433a-9eff-cd963b4c6b5d/messages"
  nats_topic = "channels"
  subtopic = ""
## mfx means that payload sent on NATS is actually Mainflux messages
## so first SenML payload will be extracted and then forwarded to MQTT
  type = "mfx"
## Number of the workers depends on the connection capacity
## as well as on payload size that needs to be sent.
## Number of workers also determines the size of the buffer
## that recieves messages from NATS.
## For regular telemetry SenML messages 10 workers is enough.
  workers = 10

